### ISSUE TITLE
3060Ti no Temp

### ISSUE THREAD

**Issue by dedizones** [cryptopoo/hiveos_gddr6x_temps#11]
Hello,

Nice script

i added 3060Ti for Trex

```
GPU 4
06:00.0
GeForce RTX 3060 Ti 7982 MB · MSI
Samsung GDDR6 · 94.04.38.00.F0 · PL 100 W, 240 W, 250 W
```

`GPU #4: RTX 3060 Ti - 164.31 MH/s, [T:32/66C, P:107W, F:50%, E:1.54MH/W], 42/42 R:0%`

![image](https://user-images.githubusercontent.com/58809062/160271786-c3f9f920-4e14-45ab-8b55-c50700c44ab9.png)

```
TREX_LOG_FILE="/var/log/miner/t-rex/t-rex.log"
TREX_REGEXP="s/GPU #[ ]*\([0-9]\{1,2\}\): RTX \(3060 Ti\|3080\|3090\|3070 Ti\|2080\|A2000\|A4000\|A4500\|A5000\).*[ \t]*\[T:[0-9]\{1,3\}\/\([0-9]\{1,3\}\)C,.*/\1,\3/p"

```

Please add fix directly in master source ;)

**Comment by cryptopoo** [comment]
Done ;)
