### ISSUE TITLE
Donation option

### ISSUE THREAD

**Issue by NucleaR-II** [cryptopoo/hiveos_gddr6x_temps#12]
is there another way to donate besides ETH ? ETH has too high fees.

Ravencoin
Ergo
Bitcoin
Paypal

THANK YOU for your hard work

**Comment by dedizones** [comment]
beer, coffe or teens lol 

> is there another way to donate besides ETH ? ETH has too high fees.
> 
> Ravencoin Ergo Bitcoin Paypal
> 
> THANK YOU for your hard work

**Comment by cryptopoo** [comment]
Hello!

Thanks for the interest in raising this topic, I already appreciate it :heart_eyes: 

I have updated the README with a bunch of addresses. I hope they are enough :rofl:

Any donation, even the smallest will represent a great token of appreciation!
We are all going to be rich anyway, one day or another :crossed_fingers:

Cheers! :beer:

P.S. For teens send me a DM; late 20s also very much appreciated :smirk:  :smirk:  :smirk: :smile:
