### ISSUE TITLE
Why not read for lolMiner API Stats?

### ISSUE THREAD

**Issue by jgonzis** [cryptopoo/hiveos_gddr6x_temps#14]
Hi, 
Nice idea I did it changing the Core Temp for Mem Temp. 
Another easy way for lolMiner is read API.

127.0.0.1:44444/summary and you have it in a json file each 10 seconds update

It could be better. What do you think?

**Comment by cryptopoo** [comment]
Hi,

believe me, I don't know why I wanted to inflict myself that pain of parsing colored log files that day, but surely I will consider switching to the API output :rofl: :rofl: :rofl: :rofl: 

Thanks for pointing it out, will update it soon!

**Comment by cryptopoo** [comment]
It's done! :partying_face: 

Thanks again for pointing it out. Let me know also if it works well for you)))

Cheers!

**Comment by jgonzis** [comment]
> It's done! 🥳
> 
> Thanks again for pointing it out. Let me know also if it works well for you)))
> 
> Cheers!

I will check it later... and feedback. I was completely surprised how the parse log you did 😊😊

**Comment by jgonzis** [comment]
Good Job...  Working great... I will try to edit agent.sh to just not use another service

**Comment by cryptopoo** [comment]
Have a look at `/hive/sbin/gpu-stats` then, it will simplify the work
