### ISSUE TITLE
Does not report for 2080 or  non-EVGA 3060ti

### ISSUE THREAD

**Issue by cbroker1** [cryptopoo/hiveos_gddr6x_temps#16]
Only reports on one of my cards, a EVGA 3060ti:
<img width="306" alt="asdf" src="https://user-images.githubusercontent.com/43118284/160323298-270df920-2375-4200-91a4-47f11eb43b31.png">
t-rex: 0.25.9
hive: 0.6-213@220325
nvidia driver: 495.46

**Comment by dedizones** [comment]
Go hiveos)>miner.log and paste stats cards

exemple for me:

![image](https://user-images.githubusercontent.com/58809062/160366804-3509ad06-3d36-4fda-8a21-fc73f59d44b8.png)

**Comment by cryptopoo** [comment]
Hello @cbroker1,

unfortunately not all of these cards report memory temperatures. As @dedizones suggests, have a look at the miner log from hive-console and see if they are reported there and attach a screenshot.
If they aren't reported by the miner, there is nothing we can do :(

**Comment by cbroker1** [comment]
Understood - I look forward to when they come available!
