### ISSUE TITLE
Inconsistent Temp Display on T-Rex

### ISSUE THREAD

**Issue by hybrdthry911** [cryptopoo/hiveos_gddr6x_temps#19]
Installed successfully via Hive Shell. At times HiveOS displays the temps, but most times it does not. This functionality appears the same across 4 rigs, 3080 LHR's and 3090s. The T-Rex miner is logging the temps without issue. 

HiveOS Version: 0.6-213@220325

**Comment by cryptopoo** [comment]
Hello,

in order to understand better your setup, can you please copy/paste the result of this command?

```
gpu-stats
```

as well as the result of this command (remove any information you may want to remove, but do leave the t-rex GPUs tables and hashrates as they are):

```
tail -n100 /var/log/miner/t-rex/t-rex.log
```

**Comment by cryptopoo** [comment]
Additionally, can you please try to install the unstable version? I just pushed a possible fix for this:

```
curl https://raw.githubusercontent.com/cryptopoo/hiveos_gddr6x_temps/main/quick-install-unstable.sh | bash
```

Would love to hear whether this works :)

**Comment by wandreis** [comment]
> Additionally, can you please try to install the unstable version? I just pushed a possible fix for this:
> 
> ```
> curl https://raw.githubusercontent.com/cryptopoo/hiveos_gddr6x_temps/main/quick-install-unstable.sh | bash
> ```
> 
> Would love to hear whether this works :)
![Screen Shot 2022-03-29 at 9 07 24 AM](https://user-images.githubusercontent.com/80705838/160618128-1ed356a4-c6c0-4997-9481-11e2c2d93732.png)

Same thing here... TREX miner, RTX 3080 and 3090 FE's.
Mem temp shows briefly on GUI after rebooting, and then disapears.
Tried with the unstable version, same thing.

**Comment by cryptopoo** [comment]
Hey @wandreis,

thanks for reporting this. I'm cleaning up many things on the way. You will see in the next hours that I pushed something on the repo. Everytime you see some new code pushed, would you mind re-installing the unstable version and promptly inform promptly me if you see the problem disappears? :)

I kinda imagine why this happens so I'm working on this.

I count on you :crossed_fingers:

**Comment by wandreis** [comment]
> Hey @wandreis,
> 
> thanks for reporting this. I'm cleaning up many things on the way. You will see in the next hours that I pushed something on the repo. Everytime you see some new code pushed, would you mind re-installing the unstable version and promptly inform promptly me if you see the problem disappears? :)
> 
> I kinda imagine why this happens so I'm working on this.
> 
> I count on you 🤞

Of course! That's the minimum that I can do for help! I'll keep my eyes open on your repo's pushes.
Thanks!

**Comment by dedizones** [comment]
i have same problem with trex last update

i try unstable version

**Comment by dedizones** [comment]
I clean with script quick-uninstall.sh and install quick-install-unstable.sh 

no temp memory

sometimes they are there sometimes not, I changed the refresh of TREX to 10sec the same


> gpu-stats

gpu-stats
{"temp":["0","43","46","43","45","45","45","44","44","40"],"fan":["0","65","65","65","65","65","65","65","65","65"],"power":["0","138","197","188","216","176","177","136","131","135"],"busids":["00:02.0","04:00.0","05:00.0","06:00.0","07:00.0","08:00.0","0a:00.0","0c:00.0","0d:00.0","0e:00.0"],"brand":["cpu","nvidia","nvidia","nvidia","nvidia","nvidia","nvidia","nvidia","nvidia","nvidia"],"load":["0","100","100","100","100","100","100","100","100","100"]}

tail -n100 /var/log/miner/t-rex/t-rex.log

![image](https://user-images.githubusercontent.com/58809062/160663791-9b5bf4f9-3b59-4b2e-8f2d-85786aa376ea.png)


EDIT:

I change in trex

`"gpu-report-interval": 60`

restart miner and it's work ??!!

**really weird this behavior after the restart the stats come back but but after a few minutes nothing**

**Comment by wandreis** [comment]
Adding a few more informations:

-I've changed from TREX to GMINER, and the mem temps seems more consistent, but sometimes it stills disappearing even on GMINER.... in this case, if I spam the refresh button it will eventually shows up again. 

I've tested on 3 rigs, all with RTX 3080 and 3090 FE GPU's. Same results on 3 rigs.

gpu-stats:

{"temp":["0","57","49","57","58","58","55","55","56","57","57","53","52"],"fan":["0","99","90","99","99","99","99","99","99","99","99","99","99"],"power":["0","221","290","319","302","302","293","302","29
3","296","222","296","220"],"busids":["00:02.0","01:00.0","02:00.0","03:00.0","04:00.0","05:00.0","07:00.0","08:00.0","09:00.0","0a:00.0","0b:00.0","0c:00.0","0d:00.0"],"brand":["cpu","nvidia","nvidia","n
vidia","nvidia","nvidia","nvidia","nvidia","nvidia","nvidia","nvidia","nvidia","nvidia"],"load":["0","100","100","100","100","100","100","100","100","100","100","100","100"]}

tail -n100 /var/log/miner/gminer/gminer.log

![Screen Shot 2022-03-29 at 1 27 48 PM](https://user-images.githubusercontent.com/80705838/160670620-8ee729a0-7b91-4f94-a03c-2e8679600280.png)
![Screen Shot 2022-03-29 at 1 28 25 PM](https://user-images.githubusercontent.com/80705838/160670639-7c251993-039b-49ba-ab2e-44e6733ed32e.png)

**Comment by cryptopoo** [comment]
Thanks for all these information.

I have been working for a while and got totally rid of parsing log files.
I now gather all temperatures data from each miner's API, which is more reliable. Additionally, I have simplified and cleaned up quite some code, so it's execution should be much faster and the patching of temperatures should happen right on time before the agent sends data to HiveOS.

Could you all please try to install the unstable/development version now?

Also, keep an eye for future pushes/commits as I will be doing small touches here and there if needed :)

:crossed_fingers: :crossed_fingers: :crossed_fingers: :crossed_fingers: :crossed_fingers:

**Comment by wandreis** [comment]
> Thanks for all these information.
> 
> I have been working for a while and got totally rid of parsing log files. I now gather all temperatures data from each miner's API, which is more reliable. Additionally, I have simplified and cleaned up quite some code, so it's execution should be much faster and the patching of temperatures should happen right on time before the agent sends data to HiveOS.
> 
> Could you all please try to install the unstable/development version now?
> 
> Also, keep an eye for future pushes/commits as I will be doing small touches here and there if needed :)
> 
> 🤞 🤞 🤞 🤞 🤞

Just installed on 3 Rigs... 
seems like it's more consistent now but stills disappearing.
Do you need the curl and gpu-info again?

**Comment by cryptopoo** [comment]
It's more consistent, but can you also provide some timing info? For example how long it takes for it to disappear? And if re-appears, after how long?

I just pushed another line that could finally help (unstable version) :crossed_fingers:

**Comment by cryptopoo** [comment]
If you can confirm it works, I will prepare a new stable release :crossed_fingers: !

**Comment by wandreis** [comment]
> It's more consistent, but can you also provide some timing info? For example how long it takes for it to disappear? And if re-appears, after how long?
> 
> 
> 
> I just pushed another line that could finally help (unstable version) :crossed_fingers: 

Think you nailed it this time!
I'm out of home but uninstalled/reinstalled the last version thru the mobile app, and seems like the temps didn't disappeared anymore. 
I'll keep my eyes on it and report in the next couple hours.

Autofan patch should work flawlessly now? I'll try to apply it.

**Comment by cryptopoo** [comment]
That's awesome :smile: :smile: :smile: :smile: !

**Comment by wandreis** [comment]
Autofan patch isn't working, think it's missing your final magic! 😜

**Comment by cryptopoo** [comment]
You may need to re-patch it again. Try the following:

```
curl https://raw.githubusercontent.com/cryptopoo/hiveos_gddr6x_temps/main/patch-autofan.sh | bash; autofan restart
```

Paste the results of the command as well :)

**Comment by wandreis** [comment]
> curl https://raw.githubusercontent.com/cryptopoo/hiveos_gddr6x_temps/main/patch-autofan.sh | bash; autofan restart

Working!
![image](https://user-images.githubusercontent.com/80705838/160719865-74b7c4d3-fd3d-4144-be6c-31804e0d43a5.png)

Let me try changing from GMINER to TREX now.

**Comment by wandreis** [comment]
GMINER / TREX / AUTOFAN ✅ 
Thanks a lot! 🙏🏼

**Comment by wandreis** [comment]
If you need any other test, please let me know.

**Comment by cryptopoo** [comment]
That's great!

I only have last few things to change (some occasional hangs in some rare situations and another issue to fix) and then I will move this to stable :)

If you like the project and would like to donate I will definitely appreciate it!

Cheers! :beers:

**Comment by ffischh** [comment]
now it works like a charm! thanks a lot!

**Comment by dedizones** [comment]
> now it works like a charm! thanks a lot!

Me Too with last unstable ;)

**Comment by 8465231** [comment]
Just wanted to say that I was also having issues with the temps disappearing after a few hours but updated to the latest unstable script and so far so good 4 hours in!

**Comment by cryptopoo** [comment]
Hello @8465231,

thanks for confirming it. When was last time you installed the other version? Was it before the 30th of March at ~1AM UTC time?

**Comment by cryptopoo** [comment]
Just wanted to remind that if this worked well for you, a small donation will be always appreciated :smiley_cat: 

Also, I just pushed a new unstable version that make use of pcie addresses to identify cards (instead of the id reported in the miner), this will produce more accurate results in some mixed AMD/NVIDIA configurations.
I could say code almost reached it's nirvana :heart:

**Comment by 8465231** [comment]
> Hello @8465231,
> 
> thanks for confirming it. When was last time you installed the other version? Was it before the 30th of March at ~1AM UTC time?

Not 100% sure but I think it was before then, it was the morning of the 30th just not sure exactly when.

**Comment by cryptopoo** [comment]
Closing this, as it seems that this doesn't happen anymore :)
