### ISSUE TITLE
error  hiveos_gddr6x_temps

### ISSUE THREAD

**Issue by UNLUNL99** [cryptopoo/hiveos_gddr6x_temps#22]
curl: (35) OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to raw.githubusercontent.com:443 

error 
How to deal with it?

**Comment by dedizones** [comment]
hello,

paste in console copy repons ?

`curl -v github.com:443`

ME i have this:

> curl -v github.com:443
> * Rebuilt URL to: github.com:443/
> *   Trying 140.82.121.4...
> * TCP_NODELAY set
> * Connected to github.com (140.82.121.4) port 443 (#0)
> > GET / HTTP/1.1
> > Host: github.com:443
> > User-Agent: curl/7.58.0-DEV
> > Accept: */*
> >
> * Empty reply from server
> * Connection #0 to host github.com left intact
> curl: (52) Empty reply from server
> 

check your firewall and update you linux 

`sudo apt-get update -y && sudo apt-get dist-upgrade -yuf`
`
sudo apt-get install nvidia-settings xserver-xorg-core --allow-change-held-packages -y`


And reboot properly ;)

**Comment by cryptopoo** [comment]
Hello!

Are you installing this from HiveOS ? That's an odd error, you should retry again and if it still doesn't work, do reinstall your HiveOS because something must be very wrong in there :)

Cheers!
