### ISSUE TITLE
Can't uninstall

### ISSUE THREAD

**Issue by angelopaulo1** [cryptopoo/hiveos_gddr6x_temps#26]
Hello! I'm trying uninstall the patch but it stills showing the temperature memory on Hive OS dashboard.

Below follow log after execute uninstall command...

main.zip                                    100%[==========================================================================================>]   8.89K  --.-KB/s    in 0s      

2022-03-31 16:39:08 (21.9 MB/s) - ‘main.zip’ saved [9103/9103]

Archive:  main.zip
39e37871c5ceb64d237d0503951919cacddc0402
   creating: hiveos_gddr6x_temps-main/
  inflating: hiveos_gddr6x_temps-main/.gitignore  
  inflating: hiveos_gddr6x_temps-main/LICENSE.md  
  inflating: hiveos_gddr6x_temps-main/README.md  
  inflating: hiveos_gddr6x_temps-main/install.sh  
   creating: hiveos_gddr6x_temps-main/opt/
   creating: hiveos_gddr6x_temps-main/opt/gddr6x_temps/
  inflating: hiveos_gddr6x_temps-main/opt/gddr6x_temps/autofan.patch  
  inflating: hiveos_gddr6x_temps-main/opt/gddr6x_temps/gddr6x_temps  
  inflating: hiveos_gddr6x_temps-main/opt/gddr6x_temps/gddr6x_temps.service  
  inflating: hiveos_gddr6x_temps-main/patch-autofan.sh  
  inflating: hiveos_gddr6x_temps-main/quick-install-unstable.sh  
  inflating: hiveos_gddr6x_temps-main/quick-install.sh  
  inflating: hiveos_gddr6x_temps-main/quick-uninstall.sh  
  inflating: hiveos_gddr6x_temps-main/uninstall.sh  
Disabling service
Removed /etc/systemd/system/gddr6x_temps.service.                                                                                                                              
Removed /etc/systemd/system/multi-user.target.wants/gddr6x_temps.service.                                                                                                      
Removing package                                                                                                                                                               
Uninstall completed

**Comment by cryptopoo** [comment]
Hello, can you please retry now?

**Comment by angelopaulo1** [comment]
Great! It worked! Thanks!

Btw, congrats for good job, we need more devs like you.

Just in case, it showed a "failed" message (below), but there were no difference in the end.

Archive:  main.zip                                                                                                                                                             
7e581c0547414a12dbbd88a266fefc91160f34ff                                                                                                                                       
   creating: hiveos_gddr6x_temps-main/                                                                                                                                         
  inflating: hiveos_gddr6x_temps-main/.gitignore                                                                                                                               
  inflating: hiveos_gddr6x_temps-main/LICENSE.md                                                                                                                               
  inflating: hiveos_gddr6x_temps-main/README.md                                                                                                                                
  inflating: hiveos_gddr6x_temps-main/install.sh                                                                                                                               
   creating: hiveos_gddr6x_temps-main/opt/                                                                                                                                     
   creating: hiveos_gddr6x_temps-main/opt/gddr6x_temps/                                                                                                                        
  inflating: hiveos_gddr6x_temps-main/opt/gddr6x_temps/autofan.patch                                                                                                           
  inflating: hiveos_gddr6x_temps-main/opt/gddr6x_temps/gddr6x_temps                                                                                                            
  inflating: hiveos_gddr6x_temps-main/opt/gddr6x_temps/gddr6x_temps.service                                                                                                    
  inflating: hiveos_gddr6x_temps-main/patch-autofan.sh                                                                                                                         
  inflating: hiveos_gddr6x_temps-main/quick-install-unstable.sh                                                                                                                
  inflating: hiveos_gddr6x_temps-main/quick-install.sh                                                                                                                         
  inflating: hiveos_gddr6x_temps-main/quick-uninstall.sh                                                                                                                       
  inflating: hiveos_gddr6x_temps-main/uninstall.sh                                                                                                                             
Disabling service                                                                                                                                                              
Failed to disable unit: Unit file gddr6x_temps.service does not exist.                                                                                                         
Removing package                                                                                                                                                               
Uninstall completed

**Comment by cryptopoo** [comment]
Thanks :smiley_cat: 

basically before it was deleting the project and disabling the service, but didn't stop the currently running process (that's why temps were still shown).

So now I added a line to stop also the currently running service. And indeed the error that you got last time is because the service was already removed with the previous uninstall command :)
