### ISSUE TITLE
Failed to connect to raw.githubusercontent.com port 443: Connection refused

### ISSUE THREAD

**Issue by Munessy** [cryptopoo/hiveos_gddr6x_temps#27]
![20220402122855](https://user-images.githubusercontent.com/102844935/161366278-3fb868e2-397f-41b7-9dc2-47434660a4bd.jpg)
help me please.
I am in China.

**Comment by cryptopoo** [comment]
Hello,

if you are in China, from your PC with proxy download this:

https://github.com/cryptopoo/hiveos_gddr6x_temps/archive/refs/tags/v1.2.0.tar.gz

and upload it somewhere in China.

Then with "Run command" in HiveOS use:

```
wget -O - "<URL of file uploaded in chinese server v1.2.0.tar.gz>" | tar -C /tmp -xzf - && cd /tmp/hiveos_gddr6x_temps-1.2.0 && 
./install.sh
```

Make sure to replace `<URL of file uploaded in chinese server v1.2.0.tar.gz>` with the URL of the file uploaded in a server reachable in China.

Hope it helps :crossed_fingers:
