### ISSUE TITLE
Make autofan work with NVIDIA memory temps FAILED

### ISSUE THREAD

**Issue by Iuriy-Budnikov** [cryptopoo/hiveos_gddr6x_temps#28]
curl https://raw.githubusercontent.com/cryptopoo/hiveos_gddr6x_temps/main/patch-autofan.sh | bash

![image](https://user-images.githubusercontent.com/3968373/161384029-0922b8c0-6775-4706-af6e-667f65445d44.png)

**Comment by cryptopoo** [comment]
Hello,

this most likely means that you are already on last version of HiveOS and that patch shouldn't be needed.

Can you please confirm this? Can you also paste the result of this command?

```
grep AUTOFAN_VERSION /hive/sbin/autofan |  head -1
```

If you are on version 3.05 you most likely won't need this patch and it should already working fine

**Comment by Iuriy-Budnikov** [comment]
@cryptopoo  you are right. I have the latest version. Thanks

![image](https://user-images.githubusercontent.com/3968373/161385483-7cdda3c9-2c03-4211-8f15-9bdb6d19eead.png)
