### ISSUE TITLE
Re:#27

### ISSUE THREAD

**Issue by Munessy** [cryptopoo/hiveos_gddr6x_temps#29]
> Hello,
> 
> if you are in China, from your PC with proxy download this:
> 
> https://github.com/cryptopoo/hiveos_gddr6x_temps/archive/refs/tags/v1.2.0.tar.gz
> 
> and upload it somewhere in China.
> 
> Then with "Run command" in HiveOS use:
> 
> ```
> wget -O - "<URL of file uploaded in chinese server v1.2.0.tar.gz>" | tar -C /tmp -xzf - && cd /tmp/hiveos_gddr6x_temps-1.2.0 && 
> ./install.sh
> ```
> 
> Make sure to replace `<URL of file uploaded in chinese server v1.2.0.tar.gz>` with the URL of the file uploaded in a server reachable in China.
> 
> Hope it helps crossed_fingers

Hello,
Because I'm in China,<https://raw.githubusercontent.com/cryptopoo/hiveos_gddr6x_temps/main/quick-install.sh>is 404.
But I used a iPhone agent to download this file.
Get the decomposition command by reading the file.
I do this:
HiveOS shell:
#!/usr/bin/env bash

wget -O - "https://github.com/cryptopoo/hiveos_gddr6x_temps/archive/refs/tags/v1.2.0.tar.gz" | tar -C /tmp -xzf - && \

cd /tmp/hiveos_gddr6x_temps-1.2.0 && \

./install.sh

-----------------------------------------------------------------------
The installation is completed!!
Finally, I have a few questions to ask.
1.Do you have a telegram?
2.Same device,t-rex yes,but lolMiner no.
3.Are there requirements for the HiveOS version?Nvidia driver? I'm 06-213@220403 now.
I mainly use lol. help me, thank you.

![QQ截图20220406095816](https://user-images.githubusercontent.com/102844935/161880487-726d0ba5-0e8d-4f4d-9fd9-873ffaf9907a.jpg)
![QQ截图20220406095350](https://user-images.githubusercontent.com/102844935/161880491-40d9ea4a-abaa-403e-91c8-366449de7592.jpg)

**Comment by cryptopoo** [comment]
Hello!

I'm glad you installed it. With lolminer running, can you run this command and paste the results?

```
curl http://127.0.0.1:44444/summary
```

You can hide from the results your address :)

**Comment by Munessy** [comment]
> 你好！
> 
> 我很高兴你安装了它。随着lollminer的运行，你能运行这个命令并粘贴结果吗？
> 
> ```
> curl http://127.0.0.1:44444/summary
> ```
> 
> 您可以隐藏您的地址的结果:)

![73704DD2-33D6-493C-9766-AD00624044B8](https://user-images.githubusercontent.com/102844935/162319771-38fc54c3-98e8-4259-989e-be1d5d8c7178.jpeg)

**Comment by cryptopoo** [comment]
Hello!

Unfortunately it seems like lolminer is not able to read memory temperatures from your graphic card, that's why it doesn't work.

You can try either to use t-rex or to uninstall this plugin (see instructions) and update HiveOS to the latest version.

**Comment by cryptopoo** [comment]
Actually, can you please run that command again after some time you mined (let's say after 5 minutes mining) and see if Juc_Temp reports any value higher than 65-70?

**Comment by Munessy** [comment]
> Hello!
> 
> Unfortunately it seems like lolminer is not able to read memory temperatures from your graphic card, that's why it doesn't work.
> 
> You can try either to use t-rex or to uninstall this plugin (see instructions) and update HiveOS to the latest version.

lolminer mem temp is <Juc_Temp>
Can you replace these two numerical displays? [Mem→Juc] please!

**Comment by Munessy** [comment]
> Actually, can you please run that command again after some time you mined (let's say after 5 minutes mining) and see if Juc_Temp reports any value higher than 65-70?

I'm sure!
![QQ截图20220408104722](https://user-images.githubusercontent.com/102844935/162353538-a43f199b-93f6-4254-bc15-1c7cf89f6574.jpg)
![QQ截图20220408105012](https://user-images.githubusercontent.com/102844935/162353545-815c7d49-3e67-472f-9b35-6b05573bbf93.jpg)

In addition, I have 3060ti*8.t-rex no,but lolminer yes.
so..please!thanks!

**Comment by cryptopoo** [comment]
Hi!

I have updated the script. Can you please try the latest unstable version?

```
curl https://raw.githubusercontent.com/cryptopoo/hiveos_gddr6x_temps/main/quick-install-unstable.sh | bash
```

**Comment by Munessy** [comment]
> Hi!
> 
> I have updated the script. Can you please try the latest unstable version?
> 
> ```
> curl https://raw.githubusercontent.com/cryptopoo/hiveos_gddr6x_temps/main/quick-install-unstable.sh | bash
> ```

OK,I'll give you feedback after I try.

**Comment by Munessy** [comment]
> Hi!
> 
> I have updated the script. Can you please try the latest unstable version?
> 
> ```
> curl https://raw.githubusercontent.com/cryptopoo/hiveos_gddr6x_temps/main/quick-install-unstable.sh | bash
> ```

![QQ拼音截图20220411043031](https://user-images.githubusercontent.com/102844935/162638681-c8c105d7-a948-4cb5-867e-9cc3f042baf2.jpg)
It's so beautiful!
