### ISSUE TITLE
Working Perfect! Thank You

### ISSUE THREAD

**Issue by MageFibonacci** [cryptopoo/hiveos_gddr6x_temps#3]
i followed the instructions, 
everything works perfectly on mixed rig (3070/3080) with 12 gpus
Thank you very much

![Cattura](https://user-images.githubusercontent.com/93497171/159771300-e2d96848-f2be-4777-92b1-d47f1a45726b.JPG)

**Comment by cryptopoo** [comment]
Looking good!

Thanks for reporting :)
