### ISSUE TITLE
Not Working on ASUS RTX 2080 DUAL

### ISSUE THREAD

**Issue by pseudobacon** [cryptopoo/hiveos_gddr6x_temps#32]
Stats show up in the log for Gminer, but not T-Rex. Tried latest stable and unstable

![image](https://user-images.githubusercontent.com/12183854/163421867-33432aa3-4485-47c1-a741-d19a626e1223.png)

**Comment by cryptopoo** [comment]
Hi,

what version of t-rex are you using? Are the temperatures shown in t-rex log and not shown in HiveOS ?

**Comment by pseudobacon** [comment]
0.25.9. They are not shown in the log for T-Rex and not shown in HiveOS. These temperatures are from Gminer log, but they also do not show up in HiveOS

**Comment by pseudobacon** [comment]
Okay. I just upgraded to 0.25.12, and now the memory temperature is showing in the log

![image](https://user-images.githubusercontent.com/12183854/163661631-85d5a135-b8b4-4e5d-ad11-75e7adb58914.png)

**Comment by cryptopoo** [comment]
Hello!

my script relays on the miner. It takes the temperatures reported by the miner and reports them to HiveOS.
I'm glad that with latest version of t-rex temperatures are displayed correctly!

**Comment by pseudobacon** [comment]
Hi I think you misunderstood me haha. The log shows the temperatures. The temperatures are NOT showing in HiveOS
