### ISSUE TITLE
Fans 100% e não consigo desinstalar

### ISSUE THREAD

**Issue by FabioPOzinho** [cryptopoo/hiveos_gddr6x_temps#34]
Boa tarde!
Usei o comando pra desisntalar e não funcionou, minhas fans estão em 100%.
Como faço pra remover o comando, usei o indicado aqui mas não deu certo

**Comment by FabioPOzinho** [comment]
![8db484f9-ad0c-49a2-af4e-964963306d2c](https://user-images.githubusercontent.com/103782483/163683642-92cdd434-2947-47f2-96ec-aca775b2e90b.jpg)

**Comment by cryptopoo** [comment]
Hello!

The log you attached it means that simply the script is not installed anymore and nothing is left.

Did you patch autofan following the instructions in the past?

If not, then 10000000% the script is uninstalled and nothing is affecting your fans, except settings that you might have set in HiveOs.

If you patched in the past autofan module with the instructions in the README, then during uninstallation, the autofan module is reverted back to the original version, so it should be ok.

- Can you tell me more about your fans running at 100%?
- Do you have autofan enabled?
- If yes, can you show your settings and temperatures?
- What's the HiveOS version you are running?
- Can you run this command to show what version of autofan are you using?
```
grep AUTOFAN_VERSION /hive/sbin/autofan |  head -1
```

**Comment by FabioPOzinho** [comment]
Olá,

Obrigado pelo retorno.
Segue o resultado do comando indicado:
![image](https://user-images.githubusercontent.com/103782483/163687819-99aea589-7625-4c10-bb3e-0e92d10b402d.png)


![image](https://user-images.githubusercontent.com/103782483/163687834-c1a5a474-5bac-406a-95d7-bd951dfb8808.png)

![image](https://user-images.githubusercontent.com/103782483/163687867-8fe41f4f-02d8-4529-a7ca-2126938a9f96.png)

**Comment by cryptopoo** [comment]
Hello!

This confirms that you are on the latest release of autofan and that my script is completely removed from your system.

If fans stay 100%, try to increase your target and mem temperatures, as they might be too low and HiveOS tries to keep the temperatures as low as possible by setting the fans to 100%!
