### ISSUE TITLE
mixed rig / amd temps are wring

### ISSUE THREAD

**Issue by ffischh** [cryptopoo/hiveos_gddr6x_temps#4]
With a mixed rig, the amd memtemps are wrong. Can you fix this? If you need more infos, just ask. And thanks for the script.
![image](https://user-images.githubusercontent.com/102285840/159870675-0775caec-dbd9-4ad6-b426-8e3df8798a25.png)
![image](https://user-images.githubusercontent.com/102285840/159870838-b75ed2b2-9254-4f47-8300-80c3268a26a7.png)

**Comment by cryptopoo** [comment]
Hello there!

I just pushed a fix for this. In reality the temperature of other cards was not correctly updated, but rather the reading from the initial run of the script was carried over for an indefinite amount of time. That means temperatures of 40C on your AMD GPU memories were just the initial values and did not update anymore after that.

If you update the script now, it should be working.

Please report if that's the case! :pray:

**Comment by ffischh** [comment]
Yeah! Works fine! Thanks a lot! You are the best!
