### ISSUE TITLE
please add lolminer to the function that reads the Mem Temp.

### ISSUE THREAD

**Issue by pducharme** [cryptopoo/hiveos_gddr6x_temps#7]
Hi, Script worked well on both t-rex and gminer.  Can you do add lolminer readout too?

**Comment by cryptopoo** [comment]
Hi,

as soon as HiveOS will introduce lolminer 1.47 in the options, I will add it. So it's just a matter of days, I guess :)

**Comment by seblezinzin** [comment]
option added by lolminer in hiveos last version

**Comment by cryptopoo** [comment]
Hello!

lolminer 1.47 support added. Can you please re-install the module and let me know if it works fine (possibly with a screenshot)? :)

**Comment by smdbg** [comment]
Temps are displayed!  Only when miner shows them (like whit others) you have to refresh page until you see them. Issue whit autofan - auto fan scripts errors are shown now in dash everery 2-3 min (was ok, 12h ago)

![3333](https://user-images.githubusercontent.com/41722268/160269983-2083b756-c783-4bbd-86d9-494d542140a0.jpg)

**Comment by dedizones** [comment]
yes and temp CGP core and no diplayed on top

i don't see Ccore en Mcore TEMP just Mtemp

![image](https://user-images.githubusercontent.com/58809062/160273733-b3cd4b45-aceb-4f24-86b7-a33641f1aadd.png)

**Comment by cryptopoo** [comment]
> yes and temp CGP core and no diplayed on top
> 
> i don't see Ccore en Mcore TEMP just Mtemp
> 
> ![image](https://user-images.githubusercontent.com/58809062/160273733-b3cd4b45-aceb-4f24-86b7-a33641f1aadd.png)

Hi, thanks for the feedback. Can you post what your setup is like and screenshots from the miner log reporting the temperature?

**Comment by cryptopoo** [comment]
> Temps are displayed! Only when miner shows them (like whit others) you have to refresh page until you see them. Issue whit autofan - auto fan scripts errors are shown now in dash everery 2-3 min (was ok, 12h ago)
> 
> ![3333](https://user-images.githubusercontent.com/41722268/160269983-2083b756-c783-4bbd-86d9-494d542140a0.jpg)

Hello,

have a look now, it should behave behave better :)

**Comment by dedizones** [comment]
> Hello,
> 
> have a look now, it should behave behave better :)


and how to see temp core and memory on the main top hiveos

i see only memory temp :/

**Comment by cryptopoo** [comment]
Hi @dedizones,

I guess that's the way it is in HiveOS when displaying in that view. It will show the highest temperature of the two, which is 99% of the time the memory temperature, since the core temperature is way lower. From the gear icon you can change what is displayed in the table, but it doesn't seem like you can select 2 memory temperatures in there.
So we can only hope HiveOS introduces this feature. Other than this is the script working fine for you? :)

**Comment by NucleaR-II** [comment]
yes works perfectly in lolminer 1.47, thanks !!!
