### ISSUE TITLE
Support for A4500

### ISSUE THREAD

**Issue by surfjaxwave** [cryptopoo/hiveos_gddr6x_temps#8]
Can you add the A4500 in script please>?
![image](https://user-images.githubusercontent.com/102394321/160216810-5ee1566a-2a0b-409a-ae2e-d29f0e64f7a6.png)

**Comment by cryptopoo** [comment]
Hello,

I added A4500 to the list. Can you please check if it works correctly by reinstalling the module?
Please post a picture! Thank you!

**Comment by surfjaxwave** [comment]
After reinstalling I cant get any of the temps to work. I tried uninstalling and reinstalling module and used different miner that shows the temps in shell.

**Comment by cryptopoo** [comment]
Hello!

please do it again! I did commit a comment line that shouldn't have been there and the script was broken for that reason :)

**Comment by surfjaxwave** [comment]
Works great!
![image](https://user-images.githubusercontent.com/102394321/160238306-c933b4d8-fe10-4962-9129-a1960c2f0a48.png)

**Comment by cryptopoo** [comment]
Perfecto :ok_hand: :100: !

**Comment by surfjaxwave** [comment]
Forgot to tell you the temp reading using gminer for the a2000 shows 86 in shell its 70.
![Screenshot 2022-03-26 080408](https://user-images.githubusercontent.com/102394321/160238539-0949d716-d472-4b47-9827-034be838d040.png)
![Screenshot 2022-03-26 080431](https://user-images.githubusercontent.com/102394321/160238547-e100b26a-b9db-4653-a86a-9c2e5a4ad8fd.png)

**Comment by cryptopoo** [comment]
It seems like the GPU0 gets the data of GPU1.

Can you run and paste the result of this command?

```
cat "${GPU_STATS_JSON}" /run/hive/gddr6x_temp.json
```

**Comment by surfjaxwave** [comment]
Its not getting from GPU1
![image](https://user-images.githubusercontent.com/102394321/160239698-7f6d53d9-9418-4204-8f02-69526fdbee3c.png)

**Comment by surfjaxwave** [comment]
I think its something with Gminer. Trex works fine.

**Comment by cryptopoo** [comment]
if you could paste the whole result then it will make it easier for me to understand what's wrong :)

**Comment by cryptopoo** [comment]
According to your copy paste of the image it seems like is somewhat reading that value from somewhere

**Comment by surfjaxwave** [comment]
> if you could paste the whole result then it will make it easier for me to understand what's wrong :)

![image](https://user-images.githubusercontent.com/102394321/160240067-ce23b300-de87-4383-849a-fb1be55a9719.png)

**Comment by cryptopoo** [comment]
Thanks.

Are you running only one miner in your flightsheet? Or are you running t-rex and gminer at the same time for different gpus?

**Comment by surfjaxwave** [comment]
> Thanks.
> 
> Are you running only one miner in your flightsheet? Or are you running t-rex and gminer at the same time for different gpus?

Only one miner per flight sheet for all my gpus

**Comment by cryptopoo** [comment]
I'm really not sure from where that value comes from. Is it always 86C or does it change over time (try also rebooting the rig) ?

I just pushed an update on the regexp for gminer to make it more restrictive / precise, but honestly I don't think is gonna solve this. Can you please give it a try to install the module once again? (no need to run uninstall)

**Comment by surfjaxwave** [comment]
Tried reboot/install A2000 mem temp never changes from 86c but other gpu's change with the change in temps. The core temp changes though.

**Comment by cryptopoo** [comment]
Can you try to run this command and paste the result? (copy/paste the text, not image)

```
gpu-stats
```

**Comment by surfjaxwave** [comment]
> gpu-stats

gpu-stats                                                                                                                                              
{"temp":["56","52","51","57","47","52","38","49","50","49","40","47","49","48"],"fan":["90","80","80","90","60","80","80","80","60","65","0","60","60","70"],"power":["67","271
","208","119","108","176","205","123","116","118","273","110","124","115"],"busids":["01:00.0","02:00.0","03:00.0","07:00.0","08:00.0","09:00.0","0d:00.0","0e:00.0","0f:00.0",
"10:00.0","11:00.0","12:00.0","13:00.0","14:00.0"],"brand":["nvidia","nvidia","nvidia","nvidia","nvidia","nvidia","nvidia","nvidia","nvidia","nvidia","nvidia","nvidia","nvidia
","nvidia"],"load":["100","100","100","100","100","100","100","100","100","100","100","100","100","100"]}

**Comment by cryptopoo** [comment]
Great, can you also paste this? (this produces the raw numbers that the script extract from gminer log):

```
sed -ne "s/|[ ]*\([0-9]\)\{1,2\}[ ]*\(3080\|3090\|3070Ti\|2080\|A2000\|A4000\|A4500\|A5000\).*[0-9]\{1,3\}\/\([0-9]\{1,3\}\)[ ]*[0-9]\{1,3\}[ ]*%.*/\1,\3/p" /var/log/miner/gminer/gminer.log | tail -50
```

**Comment by surfjaxwave** [comment]
0,86                                                                                                                                                                           
0,68                                                                                                                                                                           
1,84                                                                                                                                                                           
2,92                                                                                                                                                                           
3,82                                                                                                                                                                           
5,76                                                                                                                                                                           
6,92                                                                                                                                                                           
0,86                                                                                                                                                                           
0,68                                                                                                                                                                           
1,84                                                                                                                                                                           
2,94                                                                                                                                                                           
3,82                                                                                                                                                                           
5,76                                                                                                                                                                           
6,92                                                                                                                                                                           
0,86                                                                                                                                                                           
0,68                                                                                                                                                                           
1,84                                                                                                                                                                           
2,92                                                                                                                                                                           
3,82                                                                                                                                                                           
5,76                                                                                                                                                                           
6,92                                                                                                                                                                           
0,86                                                                                                                                                                           
0,68                                                                                                                                                                           
1,84                                                                                                                                                                           
2,92                                                                                                                                                                           
3,82                                                                                                                                                                           
5,76                                                                                                                                                                           
6,92                                                                                                                                                                           
0,86                                                                                                                                                                           
0,68                                                                                                                                                                           
1,84                                                                                                                                                                           
2,92                                                                                                                                                                           
3,82                                                                                                                                                                           
5,74                                                                                                                                                                           
6,92                                                                                                                                                                           
0,86                                                                                                                                                                           
0,68                                                                                                                                                                           
1,84                                                                                                                                                                           
2,92                                                                                                                                                                           
3,82                                                                                                                                                                           
5,74                                                                                                                                                                           
6,92                                                                                                                                                                           
0,86                                                                                                                                                                           
0,68                                                                                                                                                                           
1,84                                                                                                                                                                           
2,92                                                                                                                                                                           
3,82                                                                                                                                                                           
5,74                                                                                                                                                                           
6,90                                                                                                                                                                           
0,86

**Comment by cryptopoo** [comment]
Now that's interesting. I see for GPU 0 that it reads both 86 and 68C.

Can you paste your last 50 lines of log from gminer so that I can do more testing?

```
tail -50 /var/log/miner/gminer/gminer.log
```

We are close to the solution :)

**Comment by surfjaxwave** [comment]
10:04:13 New Job: c5c Epoch: #482 Diff: 12.88G                                                                                                                                 
10:04:14 New Job: c5d Epoch: #482 Diff: 12.88G                                                                                                                                 
10:04:18 New Job: c5e Epoch: #482 Diff: 12.88G                                                                                                                                 
+---+-------+-----------+--------+-------+                                                                                                                                     
| ID   GPU      Speed     Shares   Best  |                                                                                                                                     
+---+-------+-----------+--------+-------+                                                                                                                                     
|  0   A2000  42.25 MH/s   39/0/0 1.513T |                                                                                                                                     
|  1    3090 118.04 MH/s   70/0/0 653.2G |                                                                                                                                     
|  2    3080  91.12 MH/s   52/0/0 583.3G |                                                                                                                                     
|  3   A4000  63.86 MH/s   44/0/0 4.820T |                                                                                                                                     
|  4    3070  60.77 MH/s   49/0/0 1.229T |                                                                                                                                     
|  5   A4500  88.10 MH/s   69/0/0 9.379T |                                                                                                                                     
|  6    3080  95.11 MH/s   76/0/0 5.016T |                                                                                                                                     
|  7  3060Ti  60.01 MH/s   25/0/0 93.48G |                                                                                                                                     
|  8    3070  61.01 MH/s   35/0/0 576.7G |                                                                                                                                     
|  9  3060Ti  60.01 MH/s   32/0/0 1.676T |                                                                                                                                     
| 10    3090 114.11 MH/s   78/0/0 1.086T |                                                                                                                                     
| 11    3070  61.05 MH/s   42/0/0 3.346T |                                                                                                                                     
| 12    3070  61.04 MH/s   47/0/0 701.4G |                                                                                                                                     
| 13  3060Ti  60.02 MH/s   42/0/0 191.0G |                                                                                                                                     
|              1.04 GH/s  700/0/0 9.379T |                                                                                                                                     
+---+-------+-----------+--------+-------+                                                                                                                                     
+---+-------+------+-----+----+-----+-----+                                                                                                                                    
| ID   GPU    Temp   Fan  Core  Mem  Kern |                                                                                                                                    
+---+-------+------+-----+----+-----+-----+                                                                                                                                    
|  0   A2000  55/70  90 %  982  7300    6 |                                                                                                                                    
|  1    3090  52/84  80 % 1065 10351    6 |                                                                                                                                    
|  2    3080  50/92  80 % 1005  9571    6 |                                                                                                                                    
|  3   A4000  57/82  90 % 1095  8250    6 |                                                                                                                                    
|  4    3070     47  60 %  690  7900    6 |                                                                                                                                    
|  5   A4500  52/76  80 % 1140  9151    6 |                                                                                                                                    
|  6    3080  38/92  80 % 1065  9951    4 |                                                                                                                                    
|  7  3060Ti     49  80 % 1365  7905    4 |                                                                                                                                    
|  8    3070     50  60 %  720  7930    6 |                                                                                                                                    
|  9  3060Ti     49  65 % 1365  7905    4 |                                                                                                                                    
| 10    3090  40/86   0 % 1035 10001    6 |                                                                                                                                    
| 11    3070     47  60 % 1050  7930    6 |                                                                                                                                    
| 12    3070     49  60 % 1035  7925    6 |                                                                                                                                    
| 13  3060Ti     48  70 % 1365  7905    6 |                                                                                                                                    
+---+-------+------+-----+----+-----+-----+                                                                                                                                                                                                                             
10:04:19 Pool Hashrate: 1.02 GH/s Efficiency: 98.54 %                                                                                                                          
10:04:19 Shares/Minute: 4.76                                                                                                                                                   
10:04:19 Uptime: 0d 02:27:11                                                                                                                                                   
10:04:20 GPU4: Share #50 verified on CPU, difficulty: 19.01G                                                                                                                   
10:04:20 GPU4: Share #50 accepted 40 ms                                                                                                                                        
10:04:22 New Job: c5f Epoch: #482 Diff: 12.88G                                                                                                                                 
10:04:22 New Job: c60 Epoch: #482 Diff: 12.88G                                                                                                                                 
10:04:22 New Job: c61 Epoch: #482 Diff: 12.88G                                                                                                                                 
10:04:22 New Job: c62 Epoch: #482 Diff: 12.88G     

I took out one line has pool info

**Comment by cryptopoo** [comment]
Awesome buddy :smile: 

That log definitely helped. There was an error in the regexp to extract the data and gpu 10 data was taken as gpu0, instead.

Now is all fixed and should work well with a new install. Thanks for all your feedback! :100: :partying_face:

**Comment by surfjaxwave** [comment]
Awesome! Glad I could help. Working properly now.
![image](https://user-images.githubusercontent.com/102394321/160243419-05030ff1-fba1-4179-8870-aeeaceb1c835.png)
